AWSTemplateFormatVersion: 2010-09-09

Description: |
  CloudFormation for Network Deployment of Capstone Project 
  - VPC
  - Subnets
  - Internet Gateway
  - NAT Gateway
  - EIP
Parameters:
  ENVIRONMENTNAME:
    Description: An environment name that will be prefixed to the resource names
    Type: String

  VPCCIDR:
    Description: Enter the CIDR for the the VPC
    Type: String
    Default: 10.0.0.0/16

  PUBSUBNET1CIDR:
    Description: Enter the CIDR for the Public Subnet 1
    Type: String
    Default: 10.0.1.0/24

  PUBSUBNET2CIDR:
    Description: Enter the CIDR for the Public Subnet 2
    Type: String
    Default: 10.0.2.0/24

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VPCCIDR
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags: 
        - 
          Key: Environment
          Value: !Ref ENVIRONMENTNAME
        -
          Key: Name
          Value: !Sub ${ENVIRONMENTNAME}-VPC
  
  INTERNETGATEWAY:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - 
          Key: Environment
          Value: !Ref ENVIRONMENTNAME
        -
          Key: Name
          Value: !Sub ${ENVIRONMENTNAME}-INTERNETGATEWAY

  INTERNETGATEWAYATT:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref INTERNETGATEWAY
      VpcId: !Ref VPC

  PUBSUBNET1:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PUBSUBNET1CIDR
      MapPublicIpOnLaunch: true
      Tags: 
        - 
          Key: Environment
          Value: !Ref ENVIRONMENTNAME
        -
          Key: Name
          Value: !Sub ${ENVIRONMENTNAME}-PUBSUBNET1
      VpcId: !Ref VPC

  PUBSUBNET2:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Ref PUBSUBNET2CIDR
      MapPublicIpOnLaunch: true
      Tags: 
        - 
          Key: Environment
          Value: !Ref ENVIRONMENTNAME
        -
          Key: Name
          Value: !Sub ${ENVIRONMENTNAME}-PUBSUBNET2
      VpcId: !Ref VPC

  PUBLICROUTETABLE:
    Type: AWS::EC2::RouteTable
    Properties: 
      Tags: 
        - Key: Environment
          Value: !Ref ENVIRONMENTNAME
        -
          Key: Name
          Value: !Sub ${ENVIRONMENTNAME}-PUBLICROUTETABLE
      VpcId: !Ref VPC

  PUBLICINTERNETROUTE:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref INTERNETGATEWAY
      RouteTableId: !Ref PUBLICROUTETABLE

  PUBLICROUTEASSOCIATION1:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
          RouteTableId: !Ref PUBLICROUTETABLE
          SubnetId: !Ref PUBSUBNET1

  PUBLICROUTEASSOCIATION2:
      Type: AWS::EC2::SubnetRouteTableAssociation
      Properties:
          RouteTableId: !Ref PUBLICROUTETABLE
          SubnetId: !Ref PUBSUBNET2

Outputs:
  StackVPC:
    Description: The ID of the VPC
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::StackName}-VPC"

  StackPUBSUBNET1:
    Description: The ID of the Public Subnet 1
    Value: !Ref PUBSUBNET1
    Export:
      Name: !Sub "${AWS::StackName}-PUBSUBNET1"

  StackPUBSUBNET2:
    Description: The ID of the Public Subnet 2
    Value: !Ref PUBSUBNET2
    Export:
      Name: !Sub "${AWS::StackName}-PUBSUBNET2"

  StackPUBSUBNETS:
    Description: A list of the Private Subnets
    Value: !Join [ ",", [ !Ref PUBSUBNET1, !Ref PUBSUBNET2 ]]
    Export:
      Name: !Sub "${AWS::StackName}-PUBSUBNETS"