apiVersion: v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: application
        image: rajxxx/capstone:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80